apiVersion: v1
kind: ConfigMap
metadata:
  name: testing-agent-config
  namespace: gocars-testing
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  AUTO_FIX_ENABLED: "true"
  API_PORT: "3000"
  METRICS_PORT: "9090"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "testing_agent"
  POSTGRES_USER: "testingagent"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: gocars-testing
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "first_rules.yml"

    scrape_configs:
      - job_name: 'testing-agent'
        static_configs:
          - targets: ['testing-agent-service:9090']
        metrics_path: /metrics
        scrape_interval: 10s

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__