# RBAC configuration for GoCars Testing Agent
apiVersion: v1
kind: ServiceAccount
metadata:
  name: testing-agent-sa
  namespace: gocars-testing
  labels:
    app: gocars-testing-agent
automountServiceAccountToken: true

---
# ClusterRole for testing agent operations
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testing-agent-cluster-role
  labels:
    app: gocars-testing-agent
rules:
# Permissions for monitoring and metrics collection
- apiGroups: [""]
  resources: ["nodes", "nodes/metrics", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]

---
# Role for namespace-specific operations
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: testing-agent-role
  namespace: gocars-testing
  labels:
    app: gocars-testing-agent
rules:
# Permissions for managing test resources
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: testing-agent-cluster-binding
  labels:
    app: gocars-testing-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testing-agent-cluster-role
subjects:
- kind: ServiceAccount
  name: testing-agent-sa
  namespace: gocars-testing

---
# RoleBinding for namespace operations
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testing-agent-binding
  namespace: gocars-testing
  labels:
    app: gocars-testing-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testing-agent-role
subjects:
- kind: ServiceAccount
  name: testing-agent-sa
  namespace: gocars-testing