apiVersion: v1
kind: Secret
metadata:
  name: testing-agent-secrets
  namespace: gocars-testing
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  FIREBASE_API_KEY: ""
  FIREBASE_PROJECT_ID: ""
  FIREBASE_AUTH_DOMAIN: ""
  FIREBASE_DATABASE_URL: ""
  FIREBASE_STORAGE_BUCKET: ""
  FIREBASE_MESSAGING_SENDER_ID: ""
  FIREBASE_APP_ID: ""
  POSTGRES_PASSWORD: dGVzdGluZ2FnZW50MTIz  # testingagent123
  GRAFANA_PASSWORD: YWRtaW4xMjM=  # admin123
---
apiVersion: v1
kind: Secret
metadata:
  name: firebase-service-account
  namespace: gocars-testing
type: Opaque
data:
  # Base64 encoded Firebase service account JSON
  service-account.json: ""